Added zstd as a compression algorithm
schollz/croc pull request #506
Opened 2022-09-13 14:40 UTC by V-R-Dighe

Related https://github.com/schollz/croc/issues/504

2022-09-13 15:40 UTC, schollz commented
I tested this patch against the current `flate` algorithm. This doesn't look like a clear improvement? 

Here are some tests run from `src/compress`.

Current version: 

```
> git checkout 1517767129b7f32e6e1c8d1caceace4fb8fda0be # current
> go test -bench=.
Level 9: 55% percent space savings
Level -2: 43% percent space savings
Level -2: 43% percent space savings
random, Level -2: -0% percent space savings
random, Level 9: -0% percent space savings
goos: linux
goarch: arm64
pkg: github.com/schollz/croc/v9/src/compress
BenchmarkCompressLevelMinusTwo-4                    1822            658837 ns/op
BenchmarkCompressLevelNine-4                        1024           1180830 ns/op
BenchmarkCompressLevelMinusTwoBinary-4                66          16841274 ns/op
BenchmarkCompressLevelNineBinary-4                    12          99928833 ns/op
```


`zstd` version:

```
> git checkout V-R-Dighe-develop
> go test -bench=.
Level 9: 53% percent space savings
Level -2: 23% percent space savings
Level -2: 23% percent space savings
random, Level -2: -0% percent space savings
random, Level 9: -0% percent space savings
goos: linux
goarch: arm64
pkg: github.com/schollz/croc/v9/src/compress
BenchmarkCompressLevelMinusTwo-4                   25466             47648 ns/op
BenchmarkCompressLevelNine-4                         214           4976949 ns/op
BenchmarkCompressLevelMinusTwoBinary-4                75          18479281 ns/op
BenchmarkCompressLevelNineBinary-4                     9         119355260 ns/op
```


For context, by default the level is `-2` (HuffmanOnly).

2022-09-15 17:04 UTC, stefins commented
Hi,
I tried the benchmark with https://github.com/klauspost/compress/zstd 
**Results**
With `github.com/DataDog/zstd`
```sh
Level 9: 53% percent space savings
Level -2: 23% percent space savings
Level -2: 23% percent space savings
random, Level -2: -0% percent space savings
random, Level 9: -0% percent space savings
goos: linux
goarch: amd64
pkg: github.com/schollz/croc/v9/src/compress
cpu: Intel(R) Celeron(R) CPU 4205U @ 1.80GHz
BenchmarkCompressLevelMinusTwo-2         	   45229	     27757 ns/op
BenchmarkCompressLevelNine-2             	     697	   1552866 ns/op
BenchmarkCompressLevelMinusTwoBinary-2   	     408	   2936133 ns/op
BenchmarkCompressLevelNineBinary-2       	      24	  54015984 ns/op
PASS
ok  	github.com/schollz/croc/v9/src/compress	6.336s
```

With `github.com/klauspost/compress/zstd`
```sh
Level 9: 52% percent space savings
Level -2: 51% percent space savings
Level -2: 51% percent space savings
random, Level -2: -0% percent space savings
random, Level 9: -0% percent space savings
goos: linux
goarch: amd64
pkg: github.com/schollz/croc/v9/src/compress
cpu: Intel(R) Celeron(R) CPU 4205U @ 1.80GHz
BenchmarkCompressLevelMinusTwo-2         	    1976	    682288 ns/op
BenchmarkCompressLevelNine-2             	     151	   8247417 ns/op
BenchmarkCompressLevelMinusTwoBinary-2   	     486	   2719676 ns/op
BenchmarkCompressLevelNineBinary-2       	     154	   8582093 ns/op
PASS
ok  	github.com/schollz/croc/v9/src/compress	8.907s
```
With current flate
```sh
Level 9: 55% percent space savings
Level -2: 43% percent space savings
Level -2: 43% percent space savings
random, Level -2: -0% percent space savings
random, Level 9: -0% percent space savings
goos: linux
goarch: amd64
pkg: github.com/schollz/croc/v9/src/compress
cpu: Intel(R) Celeron(R) CPU 4205U @ 1.80GHz
BenchmarkCompressLevelMinusTwo-2         	    3913	    300315 ns/op
BenchmarkCompressLevelNine-2             	    2180	    523972 ns/op
BenchmarkCompressLevelMinusTwoBinary-2   	     237	   4889606 ns/op
BenchmarkCompressLevelNineBinary-2       	      24	  43074478 ns/op
PASS
ok  	github.com/schollz/croc/v9/src/compress	5.103s
```

Seems like the bottleneck is with CGO calls in https://github.com/DataDog/zstd although I'm not sure 

:)

2022-09-15 17:07 UTC, stefins commented
Hi,
I tried the benchmark with https://github.com/klauspost/compress/tree/master/zstd
**Results**
With `github.com/DataDog/zstd`
```sh
Level 9: 53% percent space savings
Level -2: 23% percent space savings
Level -2: 23% percent space savings
random, Level -2: -0% percent space savings
random, Level 9: -0% percent space savings
goos: linux
goarch: amd64
pkg: github.com/schollz/croc/v9/src/compress
BenchmarkCompressLevelMinusTwo-2         	   45229	     27757 ns/op
BenchmarkCompressLevelNine-2             	     697	   1552866 ns/op
BenchmarkCompressLevelMinusTwoBinary-2   	     408	   2936133 ns/op
BenchmarkCompressLevelNineBinary-2       	      24	  54015984 ns/op
PASS
ok  	github.com/schollz/croc/v9/src/compress	6.336s
```

With `github.com/klauspost/compress/zstd`
```sh
Level 9: 52% percent space savings
Level -2: 51% percent space savings
Level -2: 51% percent space savings
random, Level -2: -0% percent space savings
random, Level 9: -0% percent space savings
goos: linux
goarch: amd64
pkg: github.com/schollz/croc/v9/src/compress
BenchmarkCompressLevelMinusTwo-2         	    1976	    682288 ns/op
BenchmarkCompressLevelNine-2             	     151	   8247417 ns/op
BenchmarkCompressLevelMinusTwoBinary-2   	     486	   2719676 ns/op
BenchmarkCompressLevelNineBinary-2       	     154	   8582093 ns/op
PASS
ok  	github.com/schollz/croc/v9/src/compress	8.907s
```
With current flate
```sh
Level 9: 55% percent space savings
Level -2: 43% percent space savings
Level -2: 43% percent space savings
random, Level -2: -0% percent space savings
random, Level 9: -0% percent space savings
goos: linux
goarch: amd64
pkg: github.com/schollz/croc/v9/src/compress
BenchmarkCompressLevelMinusTwo-2         	    3913	    300315 ns/op
BenchmarkCompressLevelNine-2             	    2180	    523972 ns/op
BenchmarkCompressLevelMinusTwoBinary-2   	     237	   4889606 ns/op
BenchmarkCompressLevelNineBinary-2       	      24	  43074478 ns/op
PASS
ok  	github.com/schollz/croc/v9/src/compress	5.103s
```

Seems like the bottleneck is with CGO calls in https://github.com/DataDog/zstd although I'm not sure 

:)

2022-09-16 03:11 UTC, stefins commented on go.mod
> +	github.com/DataDog/zstd v1.5.2
```suggestion
	github.com/klauspost/compress v1.15.9
```

2022-09-16 03:12 UTC, stefins commented on src/compress/compress.go
> +	"github.com/DataDog/zstd"
```suggestion
	"github.com/klauspost/compress/zstd"
```

2022-09-16 03:12 UTC, stefins requested changes

2022-09-16 03:12 UTC, stefins commented on src/compress/compress.go
> +	compressor := zstd.NewWriterLevel(dest, level)
```suggestion
	compressor, err := zstd.NewWriter(dest, zstd.WithEncoderLevel(zstd.EncoderLevelFromZstd(level)))
	if err != nil {
		panic(err)
	}
```

2022-09-16 03:12 UTC, stefins commented on src/compress/compress.go
> +	decompressor := zstd.NewReader(src)
```suggestion
	decompressor, err := zstd.NewReader(src)
	if err != nil {
		panic(err)
	}
```

2022-09-16 04:56 UTC, V-R-Dighe commented
Hi @stefins,
Thanks for the suggestions.
I have reflected the changes. Please have a look. 

cc @schollz.

2022-09-16 16:08 UTC, schollz commented
Really nice work @V-R-Dighe !! And thanks for clearing up that barrier @stefins !! This is a great improvement

2022-09-16 16:08 UTC, merged